expr_group: gr_football
expr_name: 10_vs_10_psro
log_dir: ../logs
seed: 0
eval_only: False

distributed:
  use: False
  auto_connect:
  auto_copy:
  nodes:
    master:
      ip: '10.103.0.119'
    workers:      
      - ip:

framework:
  name: "psro"
  max_generations: 50
  meta_solver: "nash"
  sync_training: False
  stopper:
    type: "win_rate_stopper"
    kwargs:
      min_win_rate: 0.9
      max_steps: 100
agent_manager:
  num_agents: 2
  share_policies: True

evaluation_manager:
  num_eval_rollouts: 3

policy_data_manager:
  update_func: "gr_football" 
  fields:
    payoff:
      type: "matrix"
      missing_value: -100 
    score:
      type: "matrix"
      missing_value: -100 
    win:
      type: "matrix"
      missing_value: -100 
    lose:
      type: "matrix"
      missing_value: -100 
    my_goal:
      type: "matrix"
      missing_value: -100 
    goal_diff:
      type: "matrix"
      missing_value: -100 
        
monitor:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

rollout_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  num_workers: 5
  seed: 12345
  saving_interval: 100 # the sequence of dump model's weight
  batch_size: ${rollout_manager.num_workers}
  eval_batch_size: 100
  eval_freq: 10 # epochs
  min_samples: ${training_manager.batch_size}
  rollout_metric_cfgs:
    reward:
      type: "sliding"
      window_size: 20
      init_list: [-10000]
    win:
      type: "sliding"
      window_size: 20
      init_list: [0,0,0,0,0]
  worker:
    distributed:
      resources:
        num_cpus: 1
    rollout_length: 3001
    eval_rollout_length: 3001
    sample_length: 1000
    padding_length: # of not use in gr_football
    rollout_func_name: "rollout_func"
    envs:
      - cls: "gr_football"
        id_prefix: "gr_footbal"
        scenario_config:
          env_name: "10_vs_10_kaggle"
          number_of_left_players_agent_controls: 10
          number_of_right_players_agent_controls: 10
          representation: "raw"
          rewards: "scoring, checkpoints"
          stacked: False
          logdir: '/tmp/football/malib_psro'
          write_goal_dumps: False
          write_full_episode_dumps: False
          render: False
          other_config_options:
            action_set: v2  #default/v2, v2 is only used for built-in AI
        reward_config:
          win_reward: 0
          preprocess_score: 0
          ball_position_reward: 0
          yellow_reward: 5
          min_dist_reward: 0
          goal_reward: 5
          #pass_reward: 0.02
          shot_reward: 0
          lost_ball_reward: 0.
          player_move_reward: 0.
          dist_goal_to_line: 0
          role_based_r: 0
          pure_goal: 0
          pure_lose_goal: 0
    credit_reassign:
      goal: 0.2
      assist: 0.2
      loseball: 0.05
      halt_loseball: 0.05
      gainball: 0
    decaying_exploration:
      init_noise: 0             #random exploration noise level
      total_epoch_to_zero: 2000    #number of epoch when exploration noise decay to zero
      interval: 400                #number of epoch at each fixed exploration noise level

training_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
 
  master_addr: "127.0.0.1"
  master_port:  "12774"
  local_queue_size: 1
  batch_size: 5 # how many data sample from DatasetServer per time.
  num_prefetchers: 1
  data_prefetcher:
    distributed:
      resources:
        num_cpus: 1
  num_trainers: 1
  # control the frequency of remote parameter update
  update_interval: 1
  gpu_preload: False
  trainer:
    distributed:
      resources:
        num_cpus: 1
        num_gpus: 1
        resources:
          - ["node:${distributed.nodes.master.ip}",0.01]
    optimizer: "Adam"
    actor_lr: 5.e-4
    critic_lr: 5.e-4
    opti_eps: 1.e-5
    weight_decay: 0.0
    lr_decay: False            #update_linear_schedule
    lr_decay_epoch: 2000      #how many rollout steps till zero

data_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  table_cfg:
    capacity: 1000
    sampler_type: "lumrf"
    sample_max_usage: 10000
    rate_limiter_cfg:
      min_size: ${training_manager.batch_size}
      # r_w_ratio: 10.0
  read_timeout: 120

policy_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

populations:
  - population_id: default # population_id
    algorithm:
      name: "MAPPO"
      model_config:
        model: "gr_football.basic_11"
        initialization:
          use_orthogonal: True
          gain: 1.
        actor:
          network: mlp
          layers:
            - units: 256
              activation: ReLU
            - units: 128
              activation: ReLU
            - units: 64
              activation: ReLU
          output:
            activation: False
        critic:
          network: mlp
          layers:
            - units: 256
              activation: ReLU
            - units: 128
              activation: ReLU
            - units: 64
              activation: ReLU
          output:
            activation: False

      # set hyper parameter
      custom_config:
        gamma: 1
        use_cuda: False  # enable cuda or not
        use_q_head: False
        ppo_epoch: 5
        num_mini_batch: 1  # the number of mini-batches
        
        return_mode: new_gae
        gae:
          gae_lambda: 0.95
        vtrace:
          clip_rho_threshold: 1.0
          clip_pg_rho_threshold: 100.0

        use_rnn: False
        # this is not used, instead it is fixed to last hidden in actor/critic
        rnn_layer_num: 1
        rnn_data_chunk_length: 16

        use_feature_normalization: True
        use_popart: True
        popart_beta: 0.99999

        entropy_coef: 0.00
        clip_param: 0.2
        # kl_early_stop: 0.01

        use_modified_mappo: False

      policy_init_cfg:
        agent_0: # agent_id
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0" # condition if True in order
              strategy: random # now support pretrained, inherit_last, random
              policy_id: 
              policy_dir:
            - condition: "default" # default case.
              strategy: inherit_last_best # now support pretrained, inherit_last, random
              policy_id:
              policy_dir:
          initial_policies:
            - policy_id: built_in
              policy_dir: light_malib/trained_models/gr_football/11_vs_11/built_in
#            - policy_id: current_best
#              policy_dir: light_malib/trained_models/gr_football/11_vs_11/current_best
#            - policy_id: defensive_passer
#              policy_dir: light_malib/trained_models/gr_football/11_vs_11/defensive_passer
#            - policy_id: offensive_passer
#              policy_dir: light_malib/trained_models/gr_football/11_vs_11/offensive_passer
#            - policy_id: group_pressure
#              policy_dir: light_malib/trained_models/gr_football/11_vs_11/group_pressure